steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # - name: 'gcr.io/cloud-builders/npm'
  #   args: ['test']
  #   dir: 'function/dir/from/repo/root'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - errorHandler
      - --region=us-central1
      - --source=.
      - --runtime=nodejs16
      - --trigger-http
      - --allow-unauthenticated
